# Generated by Django 4.0.5 on 2022-06-28 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, unique=True)),
                ('Year', models.CharField(max_length=10)),
                ('Released', models.CharField(max_length=50)),
                ('Runtime', models.CharField(max_length=50)),
                ('Genre', models.CharField(max_length=500)),
                ('Director', models.CharField(max_length=50)),
                ('Writer', models.TextField(max_length=500)),
                ('Actors', models.CharField(max_length=300)),
                ('Plot', models.TextField(max_length=500)),
                ('Language', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('imdb_id', models.CharField(max_length=25)),
                ('Poster', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('private', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('movies', models.ManyToManyField(blank=True, related_name='movieList', to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
